[[MagicVLSI]]
arch = "aarch64"
git-tree-sha1 = "adca0a88e8160ee174c71bda59eac8d39a358b0e"
libc = "glibc"
os = "linux"

    [[MagicVLSI.download]]
    sha256 = "d0ec03da305fddf768680e0291020099bc03124cbfce08b58957ff2b05d46197"
    url = "https://github.com/JuliaBinaryWrappers/MagicVLSI_jll.jl/releases/download/MagicVLSI-v8.3.160+0/MagicVLSI.v8.3.160.aarch64-linux-gnu.tar.gz"
[[MagicVLSI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d60704bf79dd6b6e15aaa994207cd85d91564ef1"
libc = "glibc"
os = "linux"

    [[MagicVLSI.download]]
    sha256 = "db1982797a3645292d62e82786a70b0243675e223efdbccf8afb0a2ebfcdc205"
    url = "https://github.com/JuliaBinaryWrappers/MagicVLSI_jll.jl/releases/download/MagicVLSI-v8.3.160+0/MagicVLSI.v8.3.160.armv7l-linux-gnueabihf.tar.gz"
[[MagicVLSI]]
arch = "i686"
git-tree-sha1 = "0d695de524a53d8785554b635f06e7ea003229c4"
libc = "glibc"
os = "linux"

    [[MagicVLSI.download]]
    sha256 = "f8146e589d1ab5640b013c1f26dee08a398f47c4650cff1c5219f61f21c4a4d2"
    url = "https://github.com/JuliaBinaryWrappers/MagicVLSI_jll.jl/releases/download/MagicVLSI-v8.3.160+0/MagicVLSI.v8.3.160.i686-linux-gnu.tar.gz"
[[MagicVLSI]]
arch = "powerpc64le"
git-tree-sha1 = "06cd73683ea1bc80d1027a92abf015d2c8335cbe"
libc = "glibc"
os = "linux"

    [[MagicVLSI.download]]
    sha256 = "443e2c77dfe5a79693f06270188c12308fdba4a68837d617cf67f678fedefad4"
    url = "https://github.com/JuliaBinaryWrappers/MagicVLSI_jll.jl/releases/download/MagicVLSI-v8.3.160+0/MagicVLSI.v8.3.160.powerpc64le-linux-gnu.tar.gz"
[[MagicVLSI]]
arch = "x86_64"
git-tree-sha1 = "aefd1e47baa73817521872be32181fbe4c1d51de"
libc = "glibc"
os = "linux"

    [[MagicVLSI.download]]
    sha256 = "1a93307be08f7665410956fb0401fe59f5e5b8fcc047f17a3d82188b0fa9ca3b"
    url = "https://github.com/JuliaBinaryWrappers/MagicVLSI_jll.jl/releases/download/MagicVLSI-v8.3.160+0/MagicVLSI.v8.3.160.x86_64-linux-gnu.tar.gz"
[[MagicVLSI]]
arch = "x86_64"
git-tree-sha1 = "087358a96b0ff45136fe4a65571645b406025e4e"
os = "freebsd"

    [[MagicVLSI.download]]
    sha256 = "1dbea3de8b436613cce65636434f470c097d8d09c18073ae1306b0c8496a84d8"
    url = "https://github.com/JuliaBinaryWrappers/MagicVLSI_jll.jl/releases/download/MagicVLSI-v8.3.160+0/MagicVLSI.v8.3.160.x86_64-unknown-freebsd.tar.gz"
