# Autogenerated wrapper script for MagicVLSI_jll for x86_64-linux-gnu
export tclmagic

using Tcl_jll
using GLU_jll
using Cairo_jll
using Tk_jll
JLLWrappers.@generate_wrapper_header("MagicVLSI")
JLLWrappers.@declare_library_product(tclmagic, "tclmagic.so")
function __init__()
    JLLWrappers.@generate_init_header(Tcl_jll, GLU_jll, Cairo_jll, Tk_jll)
    JLLWrappers.@init_library_product(
        tclmagic,
        "lib/magic/tcl/tclmagic.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
